### ISSUE TITLE
Exception in thread (Thread-4 and Thread-3)

### ISSUE THREAD

**Issue by mlinaje** [lagmoellertim/unsilence#18]
I tested with different parameters and video files from different sources, but I always get "Exception in thread":
PS E:\Vídeos\A procesar automaticamente\ListaAlfredoFL> unsilence '..\Lista Emu8086\08.mp4' .\acortados\01.mp4 -as 1.25 -ss 100000 -st 0.1 -ao

> Calculating Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
> 
> ┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
> ┃ Type     ┃ Before          ┃ After           ┃ Difference        ┃
> ┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
> │ Combined │ 0:03:59 (100%)  │ 0:02:39 (66.5%) │ -0:01:20 (-33.5%) │
> │ Audible  │ 0:03:18 (83.1%) │ 0:02:39 (66.5%) │ -0:00:40 (-16.6%) │
> │ Silent   │ 0:00:40 (16.9%) │ 0:00:00 (0.0%)  │ -0:00:40 (-16.9%) │
> └──────────┴─────────────────┴─────────────────┴───────────────────┘
> 
> [?] Continue with these options? (Y/n)
> Rendering Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
> Combining Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--  Exception in thread Thread-4:
> Rendering Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
> Combining Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--  Exception in thread Thread-3:
> Rendering Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   1% -:--:--
> Combining Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--

By the way, ASCII Output is wonderful ;-)
Thanks!

**Comment by lagmoellertim** [comment]
Hey, I'm pretty sure this happens because of the spaces in your path. Since python doesn't care about them, the ffmpeg command that is generated also contains these spaces. Since ffmpeg can't deal with them properly, you get an error.

Could you try unsilence on a directory that does not contain spaces anywhere in the path?
I'm going to look into fixing this issue, so that you can have spaces in paths in the future.

**Comment by mlinaje** [comment]
Thanks for the suggestion.
I have tested it without spaces right now in both right now the path and the filename, but the problem persists and it's the same (exception in the same threads).
With smaller video size still the same problem. This is one of the videos (but not the only one, I got some of them from different sources - youtube, OBS,...) that I was trying to "unsilence" where I get the exception error: https://drive.google.com/file/d/1WoxWX3qbN_87HJtY9RJQYgBNOIAa_3Yv/view?usp=sharing
Best!

**Comment by mphirke** [comment]
I tried the video that you shared (https://drive.google.com/file/d/1WoxWX3qbN_87HJtY9RJQYgBNOIAa_3Yv/view?usp=sharing). I don't get any errors on Windows 10, Python 3.8 (64-bit), FFMPEG 4.3, Unsilence 1.0.5.  

Maybe it is because of special characters(such as í ) and not just with spaces? Can you try using Unsilence in the directory the file is in instead of specifying the path in the command line? Like `unsilence 08.mp4 output.mp4`

**Comment by mlinaje** [comment]
I tried again just in d:\ using `unsilence A5.mp4 A5_unsilence.mp4 -as 1.25 -ss 10000 -sl -20 -sit 0.05 -st 0.01 ` and getting the same threads error.
I also tried with no unsilence options and it's working with no threats errors (however, for the same video file you also tested, 0% differences are observed without unsilence additional options specified.
Best!

**Comment by lagmoellertim** [comment]
Ok, I think I just found the error. It seems like speeding up the video with `-ss 10000` is too fast for ffmpeg, so try changing it to something lower (for me, 100 seems to work quite well).

I will definitely add a check for upper value limits, and probably add the value `-1` to skip it all together (next major release).
And I guess I need to spend a lot more time creating useful error logs 👍

**Comment by mlinaje** [comment]
Tested again and I agree with you @lagmoellertim ;-)
However, something else must be happening, because with other videos I tested I remember myself testing while eliminating parameter-by-parameter and the problem appeared anyway. So, maybe it's also related to Paths in some cases as you explained before...

Thanks and best to you!

**Comment by lagmoellertim** [comment]
Great that we found the fix (or at least I think we found it) 👍 
I've added the better logging and multiple other fixes to my todo list for the next release, so it hopefully should get fixed soon.
I'm going to close this for now.

Cheers!
