### ISSUE TITLE
Change or keep the name unsilence?

### ISSUE THREAD

**Issue by lagmoellertim** [lagmoellertim/unsilence#20]
Hey,
it seems like some people find the name unsilence somewhat misleading, since the function of this piece of software is not that well explained by its name. So if you think the name should be changed, feel free to write your favorite name for it in the comments (it would be great if you could also click on the poll before so that I can get an overview).

Cheers 🎉 

P.S.: If you have any ideas, please comment or add a +1 to existing comments so that I now which one you favour.

[![](https://api.gh-polls.com/poll/01EE865Q74KF11ZW2XJMPB4FBM/Keep%20the%20name%20unsilence)](https://api.gh-polls.com/poll/01EE865Q74KF11ZW2XJMPB4FBM/Keep%20the%20name%20unsilence/vote)
[![](https://api.gh-polls.com/poll/01EE865Q74KF11ZW2XJMPB4FBM/Change%20the%20name%2C%20write%20your%20favorite%20name%20in%20the%20comments)](https://api.gh-polls.com/poll/01EE865Q74KF11ZW2XJMPB4FBM/Change%20the%20name%2C%20write%20your%20favorite%20name%20in%20the%20comments/vote)

**Comment by HouQiming** [comment]
Name suggestion: skipsilence

**Comment by lagmoellertim** [comment]
Since the opinion on changing the name is about 50:50, but there is no feedback on new name choices or comments for the name suggested by @HouQiming, I will leave the name as is for now. If you don't agree, you can reopen the issue.
