### ISSUE TITLE
The program doesnt seem to like my ffmpeg

### ISSUE THREAD

**Issue by FranciscoBarCa** [lagmoellertim/unsilence#21]
**Describe the bug**

While running the example code provided on the repo I get this error.

  File "C:\Users\Fran\Desktop\Videos Clases\videoprocesss test.py", line 4, in <module>
    u = Unsilence("file_example_MP4_480_1_5MG.mp4")

  File "C:\Python38\Lib\site-packages\unsilence\Unsilence.py", line 27, in __init__
    ffmpeg_version = get_ffmpeg_version()

  File "C:\Python38\Lib\site-packages\unsilence\lib\tools\ffmpeg_version.py", line 20, in get_ffmpeg_version
    groups = match.groups()

AttributeError: 'NoneType' object has no attribute 'groups'

**Desktop (please complete the following information):**
 - OS + version:  Windows 10]
 - Python version 3.8
 - FFMPEG version 4.3
 

Im pretty new to all this, so I might be doing something wrong.
Any help would be appreciated.

**Comment by lagmoellertim** [comment]
Hey, could you send me the output of ffmpeg -version?

**Comment by FranciscoBarCa** [comment]
Thank you for the support but Ive just managed to solve it.  
The ffmpeg i had was the git version not 4.3

**Comment by AtilioA** [comment]
@lagmoellertim This will have to be addressed somehow, I'm using `ffmpeg version N-98498-gfa8345c` and it breaks unsilence (as we saw previously). But I have no idea how to fix this
