### ISSUE TITLE
Request: Add arguments to affect the "strictness" in determining the DB difference between "silent" / audible content

### ISSUE THREAD

**Issue by Marstead** [lagmoellertim/unsilence#41]
**Is your feature request related to a problem? Please describe.**
The videos I am attempting to edit do have some low-volume background music and sound effects that are significantly quieter than my voice/commentary.  This tool generally does a good job of distinguishing them but if the background music spikes slightly in volume (louder, but still nowhere near as loud as my voice) the fast forward will briefly stop during the mini-spike.

**Describe the solution you'd like**
I'd like to be able to specify an argument that affects the "silence" determination, where not specifying an argument uses the current default behavior and specifying a value makes the silence determination more or less strict based on the average volume of the entire file.

**Other solutions**
I could specify the exact dB threshold I'd like to use for "silent" vs. "audible" content, but I could see that ending up buggier than specifying a "strictness" variable, where a strictness of 5 = the default behavior (no arguments).

**Additional context**
I could share sample pre- & post-processed files showing points where small spikes in the background music that are much quieter than my commentary are treated as "audible" when I'd prefer them to be treated as "silent"; let me know the best way to share these!

**Comment by lagmoellertim** [comment]
Hey, I think there already are 2 arguments that can achieve the same thing:

```
 parser.add_argument("-sl", "--silence-level", type=float, default=-35,
                        help="Minimum volume in decibel to be classified as audible")
 parser.add_argument("-stt", "--silence-time-threshold", type=float, default=0.5,
                        help="Resolution of the silence detection (seconds)")
```

If your background music is louder than the threshold specified in --silence-level (default -35db), it is classified as "audible" eventhough there is no voice. You could try increasing this volume to e.g. -30 or -25 db, that should solve it.

The other parameter, --silence-time-threshold, is used to specifiy the minimal length an audible interval has to be in order to be classified as audible, so small spikes should be filtered out (by default these spikes can be up to 0.5 s long to be filtered out, but you can easily increase this value by passing the parameter to unsilence)

**Comment by Marstead** [comment]
Thanks again for your help on this one -- I'll take a look and possibly close this later today, but it sounds like you're describing exactly what I need.

I just now saw the "for many more settings, type -h or -help" in the readme; I assumed the example arguments in the command line usage section represented the only arguments. Is there any chance a linked with a list of arguments and their explanations could be added to the Readme? Might help block future frivolous feature requests 😂

**Comment by lagmoellertim** [comment]
Sure, I could add a table of arguments. If you want, you could start doing so and do a pr to this repo.

**Comment by Marstead** [comment]
I confirmed that the -sl and -stt arguments solved my use case. Thank you so much for your help!
