### ISSUE TITLE
Request: Add argument to specify minimum buffer (# milliseconds) before fast-forwarding starts or ends

### ISSUE THREAD

**Issue by Marstead** [lagmoellertim/unsilence#42]
**Is your feature request related to a problem? Please describe.**
In my videos, I occasionally have extremely brief sounds or noises (mouse clicks, coughs) which cause a fast-forwarded "silent" portion to briefly return to normal speed, or sometimes the fast-forwarded gap causes the cadence of speech/pausing to sound awkward.

**Describe the solution you'd like**
Add an optional argument that specifies a minimum buffer in milliseconds that must elapse before a "silent" period transitions to an "audible" transition or vice-versa.

For example, if the user sets the buffer to 1000 milliseconds, then at least 1000 milliseconds of "audible" video will need to occur before fast-forwarding ends.

**Describe alternatives you've considered**
It would be great if we had an argument both for "silent buffer" (# milliseconds of audible video in order for fast forwarding to end) and for an "audible buffer" (# milliseconds of silent video in order for fast forwarding to begin), but a global buffer setting ought to be fine.

**Additional context**
As with my feature request for an argument to control the dB, strictness of the "silent" vs. "audible" sections, I can share pre- and post-processed examples of video where this issue is present per request.

**Comment by lagmoellertim** [comment]
Hey, if I understood you right, unsilenced already has an argument for that:
```
parser.add_argument("-st", "--stretch-time", type=float, default=0.25, help="Time (seconds) that should be added to audible intervals and removed from silent " "intervals")
```

Here, before an audible interval starts, 250ms of the previous considered silent interval is made audible, and 250ms of the interval after the audible interval is considered audible. You can change the the time added to the audible intervals by changing the -st argument, it's value is given in seconds.

**Comment by Marstead** [comment]
Thanks for the help! That sounds like what I was looking for with this feature request; I'll test it for some files later today and see if it fixes, then I should be able to comment close.

Stretch-time is a single buffer for both the transition from silent to audible and back right? I could see reasons why you might want a separate argument for both.

**Comment by lagmoellertim** [comment]
Stretch-time basically adds a buffer of x seconds before and after any audible inverval (maybe I should rename the argument, buffer is much more meaningfull than stretch-time). What's the reason you want to seperate the timings for each?

**Comment by Marstead** [comment]
My request for a separate buffer might be solved by the -stt argument you mentioned in my other feature request thread. I'll do some testing today and see if that covers my use case; it's possible the existing -st buffer will work when combined with -stt.

**Comment by Marstead** [comment]
Yep, the -stt argument solved my use case. Thank you for this! This tool is saving me hundreds upon hundreds of hours of what used to be dreadful manual editing work.
