### ISSUE TITLE
unsilence fails if output path is in a new directory

### ISSUE THREAD

**Issue by belgiancoder** [lagmoellertim/unsilence#53]
**Describe the bug**
`unsilence folder1/input.mp4 folder2/output.mp4` fails if `folder2` does not exist.

**To Reproduce**
1. create  `folder1/input.mp4`
1. run `unsilence folder1/input.mp4 folder2/output.mp4`
1. `OSError: Parent directory not found`

**Expected behavior**
It should create `folder2`.

**Desktop (please complete the following information):**
 - macOS 11.0.1
 - Python 3.9.0
 - FFMPEG version 4.3.1

**Comment by alexiooo** [comment]
I would argue it is very much standard/expected behaviour for tools like this to only function if the output is in an already existing directory.

Ffmpeg itself, for example, will also fail if you supply it with a path in a non-existent directory

**Comment by belgiancoder** [comment]
Ok, maybe... I'm not used to this behavior.
Compilers, for example, create `/build` if it doesn't exist. Same for tools like `yarn` with `/node_modules` etc.

**Comment by belgiancoder** [comment]
Close this issue if it is not to be changed.

**Comment by lagmoellertim** [comment]
I think I leave it like it is, as it seems to be the default way this is handled.
Also, this avoid typos, where you tried to place the output file in an existing folder, but because of the misspelling, you created a new, unwanted folder that you need to deal with later.
