### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by Tekameikite** [lagmoellertim/unsilence#6]
`unsilence 1.mp4 2.mp4`

After trying to use it in cmd it returns: 
`AttributeError: 'NoneType' object has no attribute 'groups'`

FFmpeg in %PATH% and I'm using Windows 10 64 bit. I also tried using it with other videos but it returns the same error.

**Comment by lagmoellertim** [comment]
This seems related to the newest version I just published, could you send me the output of ffmpeg -version?

**Comment by Tekameikite** [comment]
Yeah sure:

ffmpeg version git-2020-06-10-9dfb19b Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9.3.1 (GCC) 20200523
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil      56. 52.100 / 56. 52.100
libavcodec     58. 92.100 / 58. 92.100
libavformat    58. 46.101 / 58. 46.101
libavdevice    58. 11.100 / 58. 11.100
libavfilter     7. 86.100 /  7. 86.100
libswscale      5.  8.100 /  5.  8.100
libswresample   3.  8.100 /  3.  8.100
libpostproc    55.  8.100 / 55.  8.100

**Comment by lagmoellertim** [comment]
Ah, the problem is that in order for ffmpeg to work with unsilence, it needs to be version >4.2 . It checks that with this regex:
`ffmpeg version (\d+\.\d+\.\d+)`, so it expects a valid version number in the form of number.number.number, which is not present with your version. Maybe try installing the official version of ffmpeg? (this seems to be a self build version?).
Or if you have any Idea on how to check the version number of your ffmpeg, please let me now

**Comment by Tekameikite** [comment]
Oh yeah! My mistake, I downloaded the git version instead the release one! I'll check if it works now!

**Comment by Tekameikite** [comment]
Yup, it works as intended! Thanks for help!
