### ISSUE TITLE
Define a minimum of silence to remove

### ISSUE THREAD

**Issue by Mte90** [lagmoellertim/unsilence#74]
**Is your feature request related to a problem? Please describe.**
I have a podcast and I remove manually those long silence but reading the readme seems that there is no way to define a minimum of silence to remove.

**Describe the solution you'd like**
A parameter in milliseconds will be interesting for that.

**Comment by lagmoellertim** [comment]
This can actually be done with this flag:

-stt SILENCE_TIME_THRESHOLD, --silence-time-threshold SILENCE_TIME_THRESHOLD
                        Resolution of the silence detection (seconds)
                        (default: 0.5)

Maybe I add a better flag collection to the README

**Comment by Mte90** [comment]
Thanks as I did not found anything about it.

**Comment by Mte90** [comment]
Tested and works :-D
I am trying to understand the volume of stuff to be considered silence as seems that the `-sv` is not clear how works, at least to me.

**Comment by lagmoellertim** [comment]
Yeah I think I need to better document this. `-sl` defines the decibel level below which everything is considered silent. With `-sv`, you tell the unsilence how loud you want the silent parts to be in the final output, and with `-av` you set the volume of aubible -> non-silent parts in the final output
