### ISSUE TITLE
Error reading metadata with Polish characters

### ISSUE THREAD

**Issue by mstaczek** [lagmoellertim/unsilence#86]
**Description**
An mp4 file with some Polish characters in metadata breaks unsilence.

Characters which I've found cause the error: `Ę`, `Ł`, `Ń`. Ohters such as `Ą`, `Ć`, `Ó`, `Ś`, `Ż`, `Ź` are working fine. All of these characters in lowercase are working fine (including `ę`, `ł`, `ń`). 

**To Reproduce**
1. Grab/create an mp4 file, let's call it `in.mp4`.
2. Right click on it -> Properties -> Details
3. Edit field Title or Comments and paste there at least one of: `Ę`, `Ł`, `Ń`.
4. Use command `unsilence in.mp4 out.mp4`
5. See error

**Expected behavior**
unsilence should proceed to analyzing video file.

**Error**
Error for title field containing `Ę`:
>\> unsilence in.mp4 out.mp4
Calculating Intervals... ────────────────────────────────────────   0% -:--:--
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 257: character maps to <undefined>

Error for title field containing `Ł`:
>\> unsilence in.mp4 out.mp4
Calculating Intervals... ────────────────────────────────────────   0% -:--:--
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 257: character maps to <undefined>

Full error (title metadata fields contains `Ł`):
>\> unsilence in.mp4 out.mp4 -d
Calculating Intervals... ────────────────────────────────────────   0% -:--:--
Traceback (most recent call last):
  File "c:\users\matem\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\matem\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\matem\.local\bin\unsilence.exe\__main__.py", line 7, in <module>
  File "c:\users\matem\.local\pipx\venvs\unsilence\lib\site-packages\unsilence\command_line\EntryPoint.py", line 20, in main
    run()
  File "c:\users\matem\.local\pipx\venvs\unsilence\lib\site-packages\unsilence\command_line\EntryPoint.py", line 79, in run
    **argument_dict_for_silence_detect
  File "c:\users\matem\.local\pipx\venvs\unsilence\lib\site-packages\unsilence\Unsilence.py", line 53, in detect_silence
    self.__intervals = detect_silence(self.__input_file, **kwargs)
  File "c:\users\matem\.local\pipx\venvs\unsilence\lib\site-packages\unsilence\lib\detect_silence\DetectSilence.py", line 50, in detect_silence
    for line in console_output:
  File "c:\users\matem\anaconda3\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 257: character maps to <undefined>

**Desktop (please complete the following information):**
 - OS + version: Windows 10
 - Python version: 3.7.4
 - FFMPEG version: 4.3.2
 - unsilence: 1.0.7
 

**Additional context**
My guess is that unsilence is not using right encoding when reading file metadata.

**Comment by lagmoellertim** [comment]
Hey, I don't have access to windows right now. I tried it on Linux with EasyTag and pasted in your characters, which worked without a problem. Could you send me a mp4 file with that issue?

**Comment by mstaczek** [comment]
Hi, I've prepared sample mp4 file breaking unsilence v1.0.7 - [link to google drive](https://drive.google.com/drive/folders/1mZF9P58PfDn29z6jb5VVVoNrENygFEU7?usp=sharing). Since there's been an update to 1.0.8, I'll update and check if the bug is still present.

**Comment by lagmoellertim** [comment]
I tested your files on Linux and MacOS, and neither of the files produced any error, so it seems to be a windows specific bug. I will try it out on windows asap and will get back to you

**Comment by lagmoellertim** [comment]
If you know a bit of python yourself, you could try to add the "utf-8" encoding to the spots where the error occur and check if that fixes it, I hope I can test it out till next week
