### ISSUE TITLE
Relax Python prerequisite?

### ISSUE THREAD

**Issue by RomanKornev** [lagmoellertim/unsilence#9]
Why is Python >=3.8 necessary?
Seems to be working fine on Python 3.7.7 at least (Windows 10 1909 x64):
![image](https://user-images.githubusercontent.com/5807561/84808306-2fbbf080-b011-11ea-99e2-2168cffe180e.png)

**Comment by lagmoellertim** [comment]
Yup, you're right, changed it in the repo 👍
